FOLDER: './experiments_generate_latent'

NAME: 'pulse_humanml'

TEST:
  DATASET: 'humanml3d'
  BATCH_SIZE: 1
  SPLIT: 'train'
  NUM_WORKERS: 12
  SEED_VALUE: 42

DATASET:
  SMPL_PATH: './deps/smpl'
  WORD_VERTILIZER_PATH: './deps/glove/'
  HUMANML3D:
    FRAME_RATE: 20.0
    UNIT_LEN: 4
    ROOT: './datasets/humanml3d'
  SAMPLER:
    MAX_LEN: 200
    MIN_LEN: 40
    MAX_TEXT_LEN: 20

model:
  target: []
  checkpoint_path: "/ailab/user/henantian/code/ConFiMo/humanoid/Humanoid.pth"

  t2m_textencoder:
    dim_word: 300
    dim_pos_ohot: 15
    dim_text_hidden: 512
    dim_coemb_hidden: 512

  t2m_motionencoder:
    dim_move_hidden: 512
    dim_move_latent: 512
    dim_motion_hidden: 1024
    dim_motion_latent: 512

  t2m_path: './deps/t2m/'

env:
  target: ['env_im_vae']

robot:
  target: ['smpl_humanoid']

sim:
  target: ['default_sim']

exp_name: ${NAME}
headless: True
server_mode: False
has_eval: True
no_virtual_display: False
render_o3d: False
debug: False
follow: False
add_proj: False
real_traj: False
im_eval: False

MOTION_DIR: '/ailab/user/henantian/code/ConFiMo/pulse_data/motion_set.pkl'

latent_dir: '/ailab/user/henantian/code/ConFiMo/pulse_data/latent'